// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkpHD669iYP3Bl709uSY8_c7uCmb3LyyQ',
    appId: '1:364055356261:web:a1177cdb9d590344cf378c',
    messagingSenderId: '364055356261',
    projectId: 'fir-auth-test-5d195',
    authDomain: 'fir-auth-test-5d195.firebaseapp.com',
    storageBucket: 'fir-auth-test-5d195.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoS3bo0WnT9efXN46tSWMAZa8Ehv00RnE',
    appId: '1:364055356261:android:dcbafbf9b9e082ddcf378c',
    messagingSenderId: '364055356261',
    projectId: 'fir-auth-test-5d195',
    storageBucket: 'fir-auth-test-5d195.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvPemiJcIhL5qDro-lG0w-YyFH-QWhPIA',
    appId: '1:364055356261:ios:e9ad1d1accb07a0ccf378c',
    messagingSenderId: '364055356261',
    projectId: 'fir-auth-test-5d195',
    storageBucket: 'fir-auth-test-5d195.appspot.com',
    iosClientId: '364055356261-n9iuio9hsjd7flr7pftf9vhkt68ltqu4.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterfireAuth',
  );
}
